
%CREATEFIT(T4,T1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t4
%      Y Output: t1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Jun-2015 11:00:17


%% Fit: 'untitled fit 1'.
clear
load('C:\Users\James\Desktop\Robot\enph253-2015-team13\Lab\Temp Sensor Calibration\June17TempSensorCalibration.mat')


for i = 1:6
    read(:,i) = squeeze(readings(1,i,:));
end
plot(read);

for i = 2:5
    [xData, yData] = prepareCurveData( read(1), read(1+i));

    % Set up fittype and options.
    ft = fittype( 'poly1' );
    opts = fitoptions( ft );
    opts.Lower = [-Inf -Inf];
    opts.Upper = [Inf Inf];

    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );
    coeff(i) = coeffvalues(fitresult);

end


%{
% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 't1 vs. t4', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 't4' );
ylabel( 't1' );
grid on
%}

